apiVersion: v2
name: helm-foggykitchen-hello-world-chart
description: FoggyKitchen Hello World Helm chart for OCI DevOps and OKE deployment patterns
type: application
version: 0.1.0
appVersion: "latest"
