# Default values for the FoggyKitchen Hello World Helm chart.

replicaCount: 1

image:
  repository: ghcr.io/example/foggykitchen-hello-world
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 80

loadBalancer:
  type: lb
  shape: flexible
  minShape: 10
  maxShape: 100

ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts:
    - host: foggykitchen.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
